Goal
- Find the smallest eigenvector $\lambda$ for the NC node

Problem
- Some methods too slow and/or crash on certain cases
---
Input
 - Positive definite matrix (symmetric)

Output
 - Graph cut of the matrix (corresponds to the smallest eigenvector)
---
Must
- Handle image sized inputs
- Have reproducible results (fixed seed)

In [5]:
import numpy as np
import scipy

## TODO: Begin with a simple 'image' that has a known cut, this way it can be tested if correct
## May be able to compare to sklearn.cluster.SpectralClustering (https://scikit-learn.org/stable/modules/generated/sklearn.cluster.SpectralClustering.html?highlight=lobpcg#r5f6cbeb1558e-4)

seed = 123
dtype = np.float64 # Currently doesn't do anything as random.rand doesn't accept
n = 300
# and possibly generate different sparisities?? As realistically will be somewhat sparse
in_var = 1
# in = n random numbers between 0 and 255 # probably better if its slightly realistic?
A = scipy.linalg.fiedler(in_var)

## NOTE : Could use scipy.linalg.fiedler to generate exactly what I want....



[[0.69646919 0.28613933 0.22685145 ... 0.84605484 0.12392301 0.5964869 ]
 [0.01639248 0.72118437 0.00773751 ... 0.54941306 0.02754293 0.03191799]
 [0.7013598  0.70758112 0.95993913 ... 0.84579822 0.38367275 0.06073962]
 ...
 [0.38321219 0.16822001 0.50479644 ... 0.06532379 0.10413845 0.30293511]
 [0.56015745 0.4108835  0.2613926  ... 0.68462507 0.83062849 0.45253024]
 [0.34451329 0.19109835 0.49160054 ... 0.4793873  0.75813014 0.88575846]]


[[0.69646919 0.15126591 0.46410563 ... 0.61463351 0.34204023 0.47050009]
 [0.15126591 0.72118437 0.35765932 ... 0.35881654 0.21921322 0.11150817]
 [0.46410563 0.35765932 0.95993913 ... 0.67529733 0.32253267 0.27617008]
 ...
 [0.61463351 0.35881654 0.67529733 ... 0.06532379 0.39438176 0.39116121]
 [0.34204023 0.21921322 0.32253267 ... 0.39438176 0.83062849 0.60533019]
 [0.47050009 0.11150817 0.27617008 ... 0.39116121 0.60533019 0.88575846]]


Use something similar to iterate through each eigenvector
```python
raw = 'ABC'
functions = [str.isalnum, str.isalpha, str.isdigit, str.islower,  str.isupper]

for func in functions:
    print(func(letter) for letter in raw)

In [ ]:
# Similar to https://gist.github.com/denis-bz/6a9d7379c8edf965b0a997c2ec2471e1

# used to store each of the functions, and allow them to all take the single arg input
from collections import OrderedDict
from functools import partial

# scipy and numpy are used for the eigensolvers

# TODO: reinstall scikit-sprase on mac to get it to install properly (wrong depecencies and unknown fix for mac)
# until then just dont test unless on debian system
# import sksparse 

np_sp_linalg = OrderedDict(
    ## NOTE: Will need to set the v0 to something consistent
    ## NOTE: and if neccessary any seeds used by them....
    ## NOTE: All inputs will be positive definite so should be easy :)
    
    
    # Types to try:
    # - shift invert (as we are looking for smallest) (https://gist.github.com/denis-bz/2658f671cee9396ac15cfe07dcc6657d)
    # - Power iteration, QR, LOBPCG
    # - Lanzcos, Arnoldi
    # - cholmod (https://scikit-sparse.readthedocs.io/en/latest/cholmod.html, https://stackoverflow.com/questions/59416098/finding-smallest-eigenvectors-of-large-sparse-matrix-over-100x-slower-in-scipy)
    # - any gpu based ones? (pytorch perhaps?)
    
    # Options will include the driver for each as well as the unique methods
    
    
    # The actual methods available
    # scipy.linalg.eig 
    # scipy.linalg.eigh  # Should be good
    # scipy.sparse.linalg.lobpcg
    # scipy.sparse.linalg.eigs
    # scipy.sparse.linalg.eigsh
    # sksparse.cholmod.cholesky # Should be good
    # scipy.sparse.linalg.bicg
    # scipy.sparse.linalg.gmres
    
    # scipy.sparse.linalg.splu ??
    # scipy.linalg.cholesky ??
    # scipy.linalg.qr ??
    
    # numpy.linalg.cholesky
    # numpy.linalg.qr
    # numpy.linalg.eig
    # numpy.linalg.eigh    # Should be good
    
    
    
    # Each should just take one argument (A) the input matrix
    
    # Numpy (no params only inputs)
    np_eig = np.linalg.eig,
    np_eigh = np.linalg.eigh,
    np_eigvals = np.linalg.eigvals,
    
    # Some parameters for scipy variants
    sp_eig = partial(scipy.linalg.eig, check_finite=False), # No extra params
    
    
    # TODO: think about the problem I am solving and figure which forms I should give....
    # g is the generaized problem (where b is not None)
    
    # Subset by index only for evr, evx, and gvx
    # driver sy for real
    # syev is symmetric QR (slow but robust)
    # syevr seen as optimal for most cases
    # syevd is faster for more memeroy
    # syevx could be useful for a single eigenvalue on large matricies...
    sp_eigh = partial(scipy.linalg.eigh, check_finite=False, subset_by_index=[0,0]) # driver=, type=(generalized or not), 
    # defaults to driver=syevr...
    
    
    
    
    np_eigvalsh = np.linalg.eigvalsh,  # _syevd
    sp_eigvalsh_ev = partial( scipy.linalg.eigvalsh, driver="ev" ),  # ev evd evr evx
    sp_eigvalsh_evd = partial( scipy.linalg.eigvalsh, driver="evd" ),
    sp_eigvalsh_evr = partial( scipy.linalg.eigvalsh, driver="evr" ),

        # evecs too --
    np_eigh = np.linalg.eigh,
    sp_eigh_evd = partial( scipy.linalg.eigh, driver="evd" ),
    sp_eigh_evr = partial( scipy.linalg.eigh, driver="evr" ),
        # ev evd evr evx / gv gvd gvx generalized

        # complex evals --
    np_eigvals = np.linalg.eigvals,  # _geev
    sp_eigvals = scipy.linalg.eigvals,

    np_lstsq = partial( np.linalg.lstsq, b=b, rcond=rcond ),
    sp_lstsq = partial( scipy.linalg.lstsq, b=b, cond=rcond ),

    np_solve = partial( np.linalg.solve, b=b ),
    sp_solve = partial( scipy.linalg.solve, b=b ),
    np_svd = partial( np.linalg.svd, compute_uv=False ),  # gesdd
    sp_svd = partial( scipy.linalg.svd, compute_uv=False ),  # lapack_driver : {'gesdd', 'gesvd'}
)

In [ ]:
from time import time